stages:
  - test
  - prod
before_script:
 - apt-get update -qq && apt-get install -y -qq sshpass

test:
  stage: test
  script:
  - pip install --no-cache-dir -r requirements.txt
  - pylint --rcfile=.pylintrc pybus.py pybus_test.py
  - python pybus_test.py
  except:
  - master

production:
  stage: prod
  script:
  - echo "Deploying on prod"
  - export SSHPASS=$PRODUCTION_PASSWORD
  - script -qc"shpass -e scp -vvv pybus.py $PRODUCTION_USERNAME@freebsd:/usr/local/www/apache24/api/pybus.py"
  only:
  - master
