stages:
  - test
  - prod

test:
  stage: test
  script:
  - apt-get update -qy
  - apt-get install -y python-dev python-pip
  - pip install --no-cache-dir -r requirements.txt
  - python pybus.py test

production:
  stage: prod
  script:
  - pip install --no-cache-dir -r requirements.txt
  - python pybus.py prod
  only:
  - master
