stages:
  - test
  - prod
before_script:
 - apt-get update -qq && apt-get install -y -qq sshpass

###
# TODO, add aws credentials to ci/cd
# needed to run : python pybus_test.py
###
test:
  stage: test
  script:
  - pip install --no-cache-dir -r requirements.txt
  - pylint --rcfile=.pylintrc pybus.py pybus_test.py
  - export USERS_TABLE=users-table-prod
  except:
  - master
###
# TODO, remove SCP to prod
# insted change the apache reverse proxy
###
production:
  stage: prod
  script:
  - echo "Deploying on prod"
  - export SSHPASS=$PRODUCTION_PASSWORD
  - script -qc"sshpass -e scp -oStrictHostKeyChecking=no pybus.py $PRODUCTION_USERNAME@freebsd:/usr/local/www/apache24/api/pybus.py"
  only:
  - master
