stages:
  - test
  - prod

test:
  stage: test
  script:
  - pip install --no-cache-dir -r requirements.txt
  - pylint --rcfile=.pylintrc pybus.py pybus_test.py
  - python pybus_test.py
  except:
  - master

production:
  stage: prod
  script:
  - echo "TODO"
  - echo "Deploying on prod.."
  only:
  - master
