stages:
  - test
  - prod
before_script:
 - apt-get update -qq && apt-get install -y -qq sshpass

test:
  stage: test
  script:
  - pip install --no-cache-dir -r requirements.txt
  - pylint --rcfile=.pylintrc pybus.py pybus_test.py
  - python pybus_test.py
  except:
  - master

production:
  stage: prod
  script:
  - 
  - echo "Deploying on prod"
  - export SSHPASS=$PRODUCTION_PASSWORD
  - sshpass -e ssh $PRODUCTION_USERNAME@freebsd cp /usr/local/www/apache24/api/py_bus.py /usr/local/www/apache24/api/py_bus.py.{date +'%Y-%m-%d'}
  - sshpass -e scp pybus.py $PRODUCTION_USERNAME@freebsd:/usr/local/www/apache24/api/py_bus.py
  only:
  - master
