stages:
  - test
  - prod
before_script:
 - apt-get update -qq && apt-get install -y -qq sshpass

###
# TODO, add aws credentials to ci/cd
# needed to run : python pybus_test.py
###
test:
  image: python
  stage: test
  script:
  - pip install --no-cache-dir -r requirements.txt
  - pylint --rcfile=.pylintrc pybus.py pybus_test.py
  except:
  - master
###
# TODO, remove SCP to prod
# insted change the apache reverse proxy
###
production:
  image: serverlesspolska/serverless-framework
  stage: prod
  script:
  - echo "Installing sls framework packages"
  - npm install serverless-python-requirements
  - npm install serverless-wsgi
  - npm install serverless-domain-manager
  - serverless config credentials -k $sls_key -s $sls_pass -p aws
  - echo "Deploying prod on -AWS-"
  - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
  - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
  # AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY are now available for serverless to use
  - serverless deploy
  only:
  - master
