org: jbellavance34

service: pybus
app: pybus

plugins:
  - serverless-python-requirements
  - serverless-wsgi

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1
  deploymentBucket:
    blockPublicAccess: True
functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
custom:
  wsgi:
    app: pybus.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux