org: jbellavance34
# serverless.yml

service: serverless-flask

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: pybus.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
    pythonBin: /home/brap/Python-3.6.9/python
provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'