on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8 
    - name: Install Plugin and Deploy
      uses: dhollerbach/actions.serverless-with-python-requirements@v2
      with:
        args: -c "serverless plugin install --name serverless-wsgi && serverless plugin install --name serverless-domain-manager && serverless deploy -s prod -c serverless.yml"
        entrypoint: /bin/sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

# test:
#   image: python:3.8.1-alpine
#   stage: test
#   script:
#   - pip install pylint
#   - pip install --no-cache-dir -r requirements.txt
#   - pylint --rcfile=.pylintrc pybus.py pybus_test.py
#   except:
#   - master

# production:
#   image: python:3.8.1-alpine
#   stage: prod
#   script:
#   - echo "Installing sls framework packages"
#   - apk add  --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/v3.7/main/ nodejs=8.9.3-r1
#   - npm install -g serverless
#   - npm install serverless-python-requirements
#   - npm install serverless-wsgi
#   - npm install serverless-domain-manager
#   - echo "Deploying prod on -AWS-"
#   - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
#   - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
#   - serverless deploy
#   only:
#   - master
